---
- name: Check NTP configuration
  ansible.netcommon.network_resource:
    config: "{{ hostvars[inventory_hostname]['ntp_global'] }}"   
    os_name: "{{ hostvars[inventory_hostname]['ansible_network_os'] }}"
    name: ntp_global
    state: "{{ state }}"
  register: ntp_diff
  check_mode: "{{ check_mode }}"

# - name: Display Drift Results
#   ansible.builtin.debug:
#     var: ntp_diff  # ntp_diff.results

- ansible.utils.fact_diff:
    before: "{{ ntp_diff.before }}"
    after: "{{ hostvars[inventory_hostname]['ntp_global'] }}"
  diff: "{{ diffs }}"
  delegate_to: localhost
  when: diffs == true

- name: if ntp_global drift found, open a servicenow ticket
  ansible.builtin.debug:
    msg: "NTP Global configuration drift detected on {{ inventory_hostname }}. Please investigate. Servicenow incident ticket has been created. The AAP job is {{ tower_job_id }}"
  when: ntp_diff.changed
  tags:
    - drift_alert
    - update_incident

- name: create servicenow ticket for ntp_global drift
  register: ntp_incident 
  servicenow.itsm.incident:
    caller: "service.ansible"
    state: new
    short_description: "NTP Global configuration drift detected on {{ inventory_hostname }}"
    description: "The NTP Global configuration on device {{ inventory_hostname }} has drifted from the desired state. Please investigate and remediate as necessary. The AAP job is is {{ tower_job_id }}" 
    urgency: medium
    impact: medium
    other:
      assignment_group: "Ansible West Tigers"
  when: ntp_diff.changed
  tags:
    - drift_alert
    - update_incident
  delegate_to: localhost

# - name: Print ntp incident results
#   ansible.builtin.debug:
#     var: ntp_incident
#   when: ntp_diff.changed
#   tags:
#     - drift_alert

- name: Print created NTP incident ticket number
  ansible.builtin.debug:
    msg: "The incident ticket number is {{ ntp_incident.record.number }}"
  when: ntp_diff.changed
  tags:
    - drift_alert
    - update_incident
# Prints out the incident ticket number created for NTP drift

- name: Set NTP incident ticket number stat and sys_id
  register: ntp_incident_stats
  ansible.builtin.set_stats:
    data:
      ntp_incident_ticket_number: "{{ ntp_incident.record.number }}"
      ntp_incident_sys_id: "{{ ntp_incident.record.sys_id }}"
      per_host: false   # optional: make it a single stat for the whole play
  when: ntp_diff.changed
  tags:
    - drift_alert
    - update_incident
# Set stats for NTP incident ticket number and sys_id for the next template in the workflow

- name: Print NTP incident stats
  ansible.builtin.debug:
    msg: "The sys_id is {{ ntp_incident_stats.ansible_stats.data.ntp_incident_sys_id }}"
  when: ntp_diff.changed
  tags:
    - drift_alert
    - update_incident
# Print out the NTP incident sys_id for verification

- name: Runs when updating an incident
  tags:
    - always
  block:

    # - name: Retrieve requested item incident sysid for each ticket
    #   when: ntp_diff.changed
    #   register: result
    #   servicenow.itsm.api_info:
    #     resource: incident
    #     sysparm_query: "numberSTARTSWITH{{ ntp_incident_ticket_number }}"

    # - name: Print the result
    #   when: ntp_diff.changed
    #   ansible.builtin.debug:
    #     var: result

    - name: Update the incident item work notes and state in ServiceNow
      when: ntp_diff.changed
      tags:
        - patch 
        - update_incident
      servicenow.itsm.api:
        action: patch
        resource: incident
        sys_id:  "{{ ntp_incident_sys_id }}" #"{{ result.record[0].sys_id }}"
        data:
          close_code: "{{ update_incident_close_code | default(omit) }}"
          close_notes: "{{ update_incident_close_notes | default(omit) }}"
          incident_state: "{{ update_incident_incident_state | default(omit) }}"