---
- name: Drift Check for Router settings
  hosts: network
  gather_facts: false
  vars:
   resource: 
     - ntp_global
     - logging_global
     - snmp_server

  tasks:
    - name: Run Drift Roles
      ansible.builtin.include_role:
        name: "roles/{{ role_item }}"
      loop: "{{ resource }}"
      loop_control:
        loop_var: role_item
...