---
- name: Register the Network Drift execution environment
  hosts: localhost
  gather_facts: false
  
  tasks:
    - name: network_drift_ee
      ansible.controller.execution_environment:
        name: network_drift_ee
        image: "{{ network_drift_ee_image | default('quay.io/locust61/network-ee:02') }}"
        organization: "{{ aap_organization | default('Red Hat network organization') }}"
